using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Http;

namespace HttpParrot
{
    public static class RecordAndReplayEnabledMessageHandlerExtensions
    {
        /// <summary>
        /// Adds a <see cref="RecordAndReplayEnabledMessageHandler"/> to all clients generated by the default <see cref="IHttpClientFactory"/>,
        /// by configuring the <see cref="HttpClientFactoryOptions"/>.
        /// </summary>
        /// <param name="recordAndRelayOptions">Options for the <see cref="RecordAndReplayEnabledMessageHandler"/>.</param>
        /// <returns></returns>
        public static IServiceCollection AddRecordAndReplayEnabledMessageHandlerToDefaultHttpClientFactory(this IServiceCollection services, RecordAndRelayOptions recordAndRelayOptions)
        {
            return services.ConfigureAll<HttpClientFactoryOptions>(options =>
            {
                options.HttpMessageHandlerBuilderActions.Add(builder =>
                {
                    builder.AdditionalHandlers.Add(new RecordAndReplayEnabledMessageHandler(recordAndRelayOptions));
                });
            });
        }
    }
}